_wandb:
    value:
        cli_version: 0.21.0
        e:
            3ft92nga1gvrul1cytoq6c2eg08d4c2t:
                args:
                    - --dataset
                    - cnn_dailymail
                codePath: training/train_transformer.py
                codePathLocal: training/train_transformer.py
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "250685575168"
                        used: "227017388032"
                email: ebebeclarence55@gmail.com
                executable: /Users/roipaname/Desktop/Generative AI/venv/bin/python
                git:
                    commit: 86b9574413af4f5ae2ac25d947e754ab3a9e8efc
                    remote: https://github.com/roipaname/Generative-AI.git
                host: rois-MacBook-Pro.local
                memory:
                    total: "8589934592"
                os: macOS-13.7.6-x86_64-i386-64bit
                program: /Users/roipaname/Desktop/Generative AI/training/train_transformer.py
                python: CPython 3.10.18
                root: /Users/roipaname/Desktop/Generative AI
                startedAt: "2025-07-31T14:50:50.715747Z"
                writerId: 3ft92nga1gvrul1cytoq6c2eg08d4c2t
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
            "3":
                - 13
            "4": 3.10.18
            "5": 0.21.0
            "6": 4.54.1
            "12": 0.21.0
            "13": darwin-x86_64
